version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/hosts:/etc/nginx/conf.d
            - ./public:/var/public
            - ./docker/logs:/var/log/nginx
        links:
            - php
    php:
        build: ./docker/images/php
        links:
            - mysql
        volumes:
            - ./public:/var/public
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mysql
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"